### ISSUE TITLE
Question au sujet des horaires ....

### ISSUE THREAD

**Issue by zfpggz** [SylvainPhilipona/Recuperation-des-AutoEvaluations#1]
Bonjour,
Est-ce normal que le lundi se termine à 16h plutôt qu'à 16h35 ?
Je me suis permis de le changer.
Si vous êtes d'accord, il convient de modifier les autres jours...
Merci d'avance de votre réponse et cordiales salutations
GGZ

**Comment by SylvainPhilipona** [comment]
Oui je me suis trompé je vais corriger les horaires

**Comment by SylvainPhilipona** [comment]
Modification terminée
