### ISSUE TITLE
Remerciements ...

### ISSUE THREAD

**Issue by zfpggz** [SylvainPhilipona/Recuperation-des-AutoEvaluations#5]
Bonjour Sylvain :-)
J'espère que vous allez bien !
Voilà une semaine que j'ai terminé mes activités, mais mon esprit vagabonde encore ;-)
Je me suis permis de tirer la version actuelle de votre production de système d'auto-évaluations, et je l'ai testé sur mon pc privé avec W11 famille. Tout a parfaitement fonctionné, et je vous félicite de la facilité qu'il y a de mettre votre dispositif en œuvre :-)
Je doute que j'en aie vraiment besoin, mais on ne sait jamais...
Alors, Sylvain, bonne suite et mes meilleurs vœux de succès pour votre tpi et fin de cfc
Cordiales salutations
G Gruaz (mailto:ggruaz@yahoo.com , +41 79 3387808)

**Comment by SylvainPhilipona** [comment]
Bonjour Monsieur Gruaz,
Je vais très bien et vous ?

Je vous remercie grandement pour votre retour !
Le projet à commencé à être utilisé notamment par Monsieur Lymberis.
J'ai aussi obtenu la note de 6 !

J'espère vous recroiser d'ici la fin de ma formation.
Bonne suite !
Sylvain Philipona
